---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps/finalizers
  verbs:
  - update
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps/status
  verbs:
  - get
  - patch
  - update
