# permissions for end users to edit simpleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simpleapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-simple-operator
    app.kubernetes.io/part-of: k8s-simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapp-editor-role
rules:
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps/status
  verbs:
  - get
