# permissions for end users to view simpleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simpleapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-simple-operator
    app.kubernetes.io/part-of: k8s-simple-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapp-viewer-role
rules:
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.peter.gyuk
  resources:
  - simpleapps/status
  verbs:
  - get
