name: GitHub Actions k8s-simple-operator CI
run-name: k8s-simple-operator CI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy
        run: make docker-build docker-push IMG=ghcr.io/${{ github.repository_owner }}/k8s-simple-operator:latest
